//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        public int KullanıcıID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string IdentityNo { get; set; }
        public string Address { get; set; }
        public string Role { get; set; }
        public string eposta { get; set; }
    
        public virtual Resimler Resimler { get; set; }
    }
}
